#!/usr/bin/php
<?php
/** _    _          ___           __ _     (R)
 * | |  (_)_ _____ / __|___ _ _  / _(_)__ _
 * | |__| \ V / -_) (__/ _ \ ' \|  _| / _` |
 * |____|_|\_/\___|\___\___/_||_|_| |_\__, |
 *                                    |___/
 * LiveConfig Web Application Installer (LC WAI)
 * Web-App-Name: phpMyAdmin
 * Web-App-Version: 5.2.2
 * @author Christoph Russow, Klaus Keppler
 * @copyright Copyright (c) 2009-2025 LiveConfig GmbH
 * @version 1.0
 * --------------------------------------------------------------------------
 */

define('WAI_INCLUDE', 'yes');
require_once("installer.inc.php");
if (!version_compare(WAI_API_VERSION, "1.0.2", ">=")) { die("ERROR Wrong API version in installer library - please update your LiveConfig installation!\n"); }
# if (!version_compare(PHP_VERSION, "5.5.0", ">=")) { die("ERROR PHP < 5.5.0 is not supported! (Current Version: ". PHP_VERSION .")"); }
if (!extension_loaded("mysqli")) { die("ERROR MySQLi Extension required but not loaded!"); }
$installer = new Installer();


/*
 * Configuration starts here
 */

$LCWAI_APPINFOS = array(
  'name' => "phpMyAdmin",
  'icon' => "ico-phpmyadmin.svg",
  'version' => "5.2.2",
  'version_major' => 5,
  'version_minor' => 2,
  'version_patch' => 2,
  'version_extra' => 0,
  'inst_name' => "wai-phpmyadmin-5.2.2-1.php",
  'inst_version' => 2,
  'release_date' => "2025-01-21 00:00:00",
  'rq_mysql_min' => "5.5",
  'rq_mysql_max' => null,
  'rq_php_min' => "7.2.0",
  'rq_php_max' => null,
  'title' => array(
    'de' => "phpMyAdmin",
    'en' => "phpMyAdmin",
  ),
  'desc_short' => array(
    'de' => "Programmierung",
    'en' => "Programmierung",
  ),
  'desc_long' => array(
    'de' => "phpMyAdmin ist eine freie Software zur Verwaltung von MySQL-Datenbanken über eine Weboberfläche. phpMyAdmin ermöglicht die Verwaltung von Tabellen, Feldern, Beziehungen, Indexen, Benutzern und Berechtigungen sowie die direkte Ausführung beliebiger SQL-Befehle.",
    'en' => "phpMyAdmin is a free software tool, intended to handle the administration of MySQL over a web interface. phpMyAdmin supports managing tables, fields, relations, indexes, users and permissions as well as executing any SQL statement.",
  ),
  'vendor_url' => array(
    'de' => "http://www.phpmyadmin.net",
    'en' => "http://www.phpmyadmin.net",
  ),
);

/* Files to download */
$LCWAI_DOWNLOADS['ALL'] = array( // Downloads for ALL languages
  'PACKAGE' => array('NAME' => 'phpMyAdmin-5.2.2-all-languages.tar.gz',
                     'SHA1' => 'b5b75e45c9012025dc376c42e51da0dd242e5b74',
                     'URL'  => 'https://files.phpmyadmin.net/phpMyAdmin/5.2.2/phpMyAdmin-5.2.2-all-languages.tar.gz'),
);

/* Variables Liveconfig has to ask the user */
$LCWAI_USER_VARS = array();

/*
 * Program logic
 *   starts here
 */
switch($argv[1]) {
  case 'getvars':
    $installer->wai_getvars($LCWAI_USER_VARS);
    break;
  case 'install':
    wai_install();
    break;
  case 'uninstall':
    wai_uninstall();
    break;
  case 'update':
    wai_update();
    break;
  case 'download':
    $installer->wai_download($LCWAI_DOWNLOADS);
    break;
  case 'getversion':
    wai_getversion();
    break;
  case 'getrepo':
    print json_encode($LCWAI_APPINFOS);
    break;
  default:
    print "Usage ".$argv[0]." getvars|install|uninstall|update|download|getversion\n";
    exit;
}

exit;

/*
 * Definition of package specific functions
 *  starts here
 */

/*
 * wai_install()
 *   installs the package
 */
function wai_install() {
  global $LCWAI_DOWNLOADS;
  global $installer;

  $required = array('LC_DST', 'LC_SRC', 'LC_LANG', 'LC_MYSQL_DB', 'LC_MYSQL_USER', 'LC_MYSQL_PW', 'LC_MYSQL_HOST', 'LC_RUN_AS_USER');
  $optional = array('LC_MYSQL_PORT');
  if(($vars = $installer->get_env_vars($required, $optional)) === false) {
    return;
  }

  if(!is_dir($vars['LC_DST'])) {
    print "ERROR destination not a directory\n";
    return;
  }

  //extract archive
  if($installer->package_extract($vars['LC_DST'], $vars['LC_SRC'].'/'.$LCWAI_DOWNLOADS['ALL']['PACKAGE']['NAME']) === false) {
    return;
  }

  //move files out of "root"-directory
  if($installer->move($vars['LC_DST']."/phpMyAdmin-5.2.2-all-languages/*", $vars['LC_DST']."/") === false) {
    return;
  }

  //remove the "root"-directory
  if($installer->remove($vars['LC_DST']."/phpMyAdmin-5.2.2-all-languages") === false) {
    return;
  }

  date_default_timezone_set('Europe/Berlin');
  //write config file
  $config_contents = "<?php\n"
                   . "/*\n"
                   . " * Generated configuration file\n"
                   . " * Generated by: LiveConfig\n"
                   . " * Date: ".date("r")."\n"
                   . " */\n"
                   . "/* Servers configuration */\n"
                   . "\$i = 0;\n"
                   . "\n"
                   . "/* Server: testserver [1] */\n"
                   . "\$i++;\n"
                   . "\$cfg['Servers'][\$i]['verbose'] = '".$vars['LC_MYSQL_HOST']."';\n"
                   . "\$cfg['Servers'][\$i]['host'] = '".$vars['LC_MYSQL_HOST']."';\n"
                   . "\$cfg['Servers'][\$i]['port'] = '".$vars['LC_MYSQL_PORT']."';\n"
                   . "\$cfg['Servers'][\$i]['connect_type'] = 'tcp';\n"
                   . "\$cfg['Servers'][\$i]['extension'] = '".(extension_loaded('mysqli') ? "mysqli" : "mysql")."';\n"
                   . "\$cfg['Servers'][\$i]['compress'] = true;\n"
                   . "\$cfg['Servers'][\$i]['auth_type'] = 'cookie';\n"
                   . "\$cfg['Servers'][\$i]['user'] = '';\n"
                   . "\$cfg['Servers'][\$i]['password'] = '';\n"
                   . "\$cfg['Servers'][\$i]['pmadb'] = '".$vars['LC_MYSQL_DB']."';\n"
                   . "\$cfg['Servers'][\$i]['controlhost'] = '".$vars['LC_MYSQL_HOST']."';\n"
                   . "\$cfg['Servers'][\$i]['controluser'] = '".$vars['LC_MYSQL_USER']."';\n"
                   . "\$cfg['Servers'][\$i]['controlpass'] = '".$vars['LC_MYSQL_PW']."';\n"
                   . "\$cfg['Servers'][\$i]['bookmarktable'] = 'pma__bookmark';\n"
                   . "\$cfg['Servers'][\$i]['relation'] = 'pma__relation';\n"
                   . "\$cfg['Servers'][\$i]['userconfig'] = 'pma__userconfig';\n"
                   . "\$cfg['Servers'][\$i]['table_info'] = 'pma__table_info';\n"
                   . "\$cfg['Servers'][\$i]['column_info'] = 'pma__column_info';\n"
                   . "\$cfg['Servers'][\$i]['history'] = 'pma__history';\n"
                   . "\$cfg['Servers'][\$i]['recent'] = 'pma__recent';\n"
                   . "\$cfg['Servers'][\$i]['table_uiprefs'] = 'pma__table_uiprefs';\n"
                   . "\$cfg['Servers'][\$i]['tracking'] = 'pma__tracking';\n"
                   . "\$cfg['Servers'][\$i]['table_coords'] = 'pma__table_coords';\n"
                   . "\$cfg['Servers'][\$i]['pdf_pages'] = 'pma__pdf_pages';\n"
                   . "\$cfg['Servers'][\$i]['designer_coords'] = 'pma__designer_coords';\n"
                   . "\$cfg['Servers'][\$i]['favorite'] = 'pma__favorite';\n"
                   . "\$cfg['Servers'][\$i]['users'] = 'pma__users';\n"
                   . "\$cfg['Servers'][\$i]['usergroups'] = 'pma__usergroups';\n"
                   . "\$cfg['Servers'][\$i]['navigationhiding'] = 'pma__navigationhiding';\n"
                   . "\$cfg['Servers'][\$i]['savedsearches'] = 'pma__savedsearches';\n"
                   . "\n"
                   . "/* End of servers configuration */\n"
                   . "\n"
                   . "\$cfg['blowfish_secret'] = '".$installer->get_random_str(40)."';\n"
                   . "\$cfg['LoginCookieRecall'] = false;\n"
                   . "\$cfg['Import']['charset'] = 'utf-8';\n"
                   . "\$cfg['Export']['charset'] = 'utf-8';\n"
                   . "\$cfg['DefaultLang'] = '".$vars['LC_LANG']."';\n"
                   . "\$cfg['ServerDefault'] = 1;\n"
                   . "?>\n";

  $filename = $vars['LC_DST']."/config.inc.php";
  file_put_contents($filename, $config_contents);

  if(($queries = $installer->split_sqlfile($vars['LC_DST']."/sql/create_tables.sql")) === false) {
    print "ERROR while importing control table file\n";
    return;
  }

  if(!empty($queries)) {


    $dbh = new mysqli($vars['LC_MYSQL_HOST'], $vars['LC_MYSQL_USER'], $vars['LC_MYSQL_PW'], $vars['LC_MYSQL_DB']);

    if($dbh->connect_error !== null) {
      print "ERROR while connecting to database: ". $dbh->connect_error ."\n";
      return;
    }

    if(!$dbh->set_charset("utf8")) {
      print "Error while selecting database connection charset: ". $dbh->error ."\n";
      return;
    }

    foreach($queries as $query) {
      if(!preg_match("/^CREATE DATABASE/", $query) && !preg_match("/^USE/", $query)) {
        if($dbh->query($query) === false) {
          print "ERROR while executing query (".$query.")\n";
          $dbh->close();
          return;
        }
      }
    }

    $dbh->close();
  }

  print "OK\n";
}

/*
 * wai_update()
 *   updates the package
 */
function wai_update() {
  global $LCWAI_DOWNLOADS;
  global $installer;

  if(($vars = $installer->get_env_vars(array('LC_SRC', 'LC_DST', 'LC_LANG', 'LC_RUN_AS_USER'))) === false) {
    return;
  }

  if(!is_dir($vars['LC_DST'])) {
    print "ERROR destination not a directory\n";
    return;
  }

  //since mediawiki is easy to update we don't need to check the current version here
  //extract archive
  if($installer->package_extract($vars['LC_DST'], $vars['LC_SRC'].'/'.$LCWAI_DOWNLOADS['ALL']['PACKAGE']['NAME']) === false) {
    return;
  }

  if($installer->copy($vars['LC_DST']."/phpMyAdmin-5.2.2-all-languages/*", $vars['LC_DST']."/") === false) {
    return;
  }

  //remove the "root"-directory
  if($installer->remove($vars['LC_DST']."/phpMyAdmin-5.2.2-all-languages") === false) {
    return;
  }

  print "OK\n";
}


/*
 * wai_uninstall()
 *   deinstalls the package
 */
function wai_uninstall() {
  global $installer;
  if(($vars = $installer->get_env_vars(array('LC_DST'))) === false) {
    return;
  }

  if($installer->remove($vars['LC_DST']."/*") === false) {
    return;
  }

  print "OK\n";
}

/*
 * wai_getversion()
 *   returns the current installed package version
 */
function wai_getversion() {
  global $installer;

  if(($vars = $installer->get_env_vars(array('LC_DST'))) === false) {
    return;
  }

  if(!is_dir($vars['LC_DST'])) {
    print "ERROR destination '" . $vars['LC_DST'] . "' is not a directory\n";
    return;
  }

  if(!chdir($vars['LC_DST'])) {
    print "ERROR failed to change directory!\n";
    return;
  }
  include($vars['LC_DST']."/libraries/core.lib.php");
  include($vars['LC_DST']."/libraries/Config.class.php");

  $config = new PMA_Config();

  print "OK\n";
  print "version\t".$config->get('PMA_VERSION')."\n";
}
?>
